project:
  type: website

website:
  title: "Fernando Alda Lab"
  navbar:
    center:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: join.qmd
        text: Join the Lab
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    toc: false
    css: styles.css
=======
  site-url: https://fernandoalda.github.io/
  description: "Lab website for Fernando Alda – research in evolution, systematics and biodiversity of freshwater systems"
  favicon: images/logos/Lab_logo_basic_fish_v2.png  
  

  navbar:
    logo: images/logos/Lab_logo_basic2_webnavbar_v2.png
    href: /
    right:
    # - text: "Home"
    #   href: index.html
    - text: "Research"
      href: research.qmd
    - text: "Publications"
      href: publications.qmd
    #       menu:
    #         - text: "Articles"
    #           href: publications.qmd#articles
    #         - text: "Books & Book Chapters"
    #           href: publications.qmd#books-book-chapters
    #         - text: "Popular Science"
    #           href: publications.qmd#popular-science
    #         - text: "Datasets"
    #           href: publications.qmd#datasets
    - text: "People"
      href: people.qmd
    - text: "News"
      href: news.qmd
    - text: "Gallery"
      href: gallery.qmd
    - text: "Contact"
      href: contact.qmd

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
